
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

export interface Lead {
    id: number;
    company: string;
    website: string;
    budget: string;
    need: string;
    urgency: 'High' | 'Medium' | 'Low';
    status: 'New' | 'Verified' | 'Flagged' | 'Accepted';
    timestamp: number;
    isNew?: boolean;
    // New AI Fields
    websiteGrade?: 'A+' | 'B' | 'C' | 'D';
    legitimacyScore?: number;
    smartGoal?: string; // Generated by Custom AI 2
    recommendedTier?: 'Nano' | 'Micro' | 'Macro';
}

export interface Creator {
    id: string;
    name: string;
    handle: string;
    avatar: string;
    platform: 'instagram' | 'tiktok' | 'youtube' | 'twitch';
    followers: number;
    engagementRate: number;
    location: string;
    niche: string;
    riskScore: number;
    matchScore?: number;
    // New AI Fields
    aqs: number; // Audience Quality Score (0-100)
    tier: 'Nano' | 'Micro' | 'Mid-Tier' | 'Macro' | 'Mega';
}

export interface RiskReport {
    handle: string;
    verdict: 'VERIFIED' | 'FLAGGED' | 'WARNING';
    riskScore: number;
    aqs: number; // Added AQS
    botPercentage: number;
    audienceLocation: string;
    realFollowers: number;
    engagementAuthenticity: string;
    lastScan: string;
}

export interface Campaign {
    id: number;
    title: string;
    brand: string;
    status: 'Active' | 'Negotiation' | 'Completed' | 'Draft';
    influencers: number;
    budget: string;
    progress: number;
    roi?: string;
    emv?: string; // Earned Media Value
    assignedInfluencers?: CampaignInfluencer[]; // New field for Influencer Hub
}

export interface CampaignInfluencer {
    influencerId: string;
    status: 'Pending' | 'Approved' | 'Rejected';
    clientNotes?: string;
}

export interface Influencer {
    id: string;
    name: string;
    channelLink: string;
    niche: string;
    tier: 'Nano' | 'Micro' | 'Mid-Tier' | 'Macro' | 'Mega';
    pricePerDeliverable: string; // Negotiable or fixed amount
    contactInfo: string;
    shippingAddress: string;
    // Optional fields for compatibility with existing Creator type if needed
    avatar?: string;
    followers?: number;
    engagementRate?: number;
    location?: string;
    aqs?: number;
    notes?: string;
}

export interface Message {
    id: number;
    sender: string;
    preview: string;
    time: string;
    unread: boolean;
}

// --- AI-CARA TYPES ---
export interface CRMField {
    key: string;
    label: string;
    value: string | null;
    status: 'pending' | 'extracting' | 'verified';
}

export interface AICaraMessage {
    id: number;
    sender: 'AI-CARA' | 'Client';
    text: string;
    isTyping?: boolean;
}
